### ISSUE TITLE
Can't Display Highscore

### ISSUE THREAD

**Issue by ecchodun** [syd711/vpin-extensions#3]
I'm not sure if this extension is being looked at anymore, but I can't get the high score window to display in Pinup Menu at all.  When I press my "Other" key (which is "X"), the screen flashes to a cmd window running in the background and then immediately switches back to Pinup Menu with no changes.  My log looks as follows:

12:40:21.967 [main] INFO  d.m.v.u.SystemInfo - Resolve Visual Pinball tables folder C:\Games\Visual Pinball\Tables\
12:40:21.967 [main] INFO  d.m.v.u.SystemInfo - Finished pinemhi installation check.
12:40:21.967 [main] INFO  d.m.v.u.SystemInfo - ********************************* Installation Overview ***********************************************
12:40:21.982 [main] INFO  d.m.v.u.SystemInfo - Locale:                          English (United States)
12:40:21.982 [main] INFO  d.m.v.u.SystemInfo - Charset:                         windows-1252
12:40:21.982 [main] INFO  d.m.v.u.SystemInfo - PinUP System Folder:             C:\Games\PinUPSystem                                              [OK]
12:40:21.982 [main] INFO  d.m.v.u.SystemInfo - PinUP Media Folder:              C:\Games\PinUPSystem\POPMedia                                     [OK]
12:40:21.982 [main] INFO  d.m.v.u.SystemInfo - PinUP Database File:             C:\Games\PinUPSystem\PUPDatabase.db                               [OK]
12:40:21.982 [main] INFO  d.m.v.u.SystemInfo - Visual Pinball Folder:           C:\Games\Visual Pinball                                           [OK]
12:40:21.982 [main] INFO  d.m.v.u.SystemInfo - Visual Pinball Tables Folder:    C:\Games\Visual Pinball\Tables                                    [OK]
12:40:21.982 [main] INFO  d.m.v.u.SystemInfo - Visual Pinball DirectB2S Folder: C:\Games\Visual Pinball\Tables                                    [OK]
12:40:21.982 [main] INFO  d.m.v.u.SystemInfo - Mame Folder:                     C:\Games\Visual Pinball\VPinMAME                                  [OK]
12:40:21.982 [main] INFO  d.m.v.u.SystemInfo - ROM Folder:                      C:\Games\Visual Pinball\VPinMAME\roms                             [OK]
12:40:21.982 [main] INFO  d.m.v.u.SystemInfo - NVRam Folder:                    C:\Games\Visual Pinball\VPinMAME\nvram                            [OK]
12:40:21.982 [main] INFO  d.m.v.u.SystemInfo - Pinemhi NVRam Folder:            C:\Games\Visual Pinball\VPinMAME\nvram                            [OK]
12:40:21.982 [main] INFO  d.m.v.u.SystemInfo - Pinemhi Command:                 C:\Games\VPinExtensions\pinemhi\PINemHi.exe                       [OK]
12:40:21.982 [main] INFO  d.m.v.u.SystemInfo - VPReg File:                      C:\Games\Visual Pinball\User\VPReg.stg                            [OK]
12:40:21.982 [main] INFO  d.m.v.u.SystemInfo - Extracted VPReg Folder:          C:\Games\VPinExtensions\.\VPReg                                   [OK]
12:40:21.982 [main] INFO  d.m.v.u.SystemInfo - B2S Extraction Folder:           C:\Games\VPinExtensions\.\resources\b2s                           [OK]
12:40:21.982 [main] INFO  d.m.v.u.SystemInfo - VPX Files:                       79
12:40:22.123 [main] INFO  d.m.v.u.SystemInfo - Database Game Count (VPX):       74
12:40:22.123 [main] INFO  d.m.v.u.SystemInfo - *******************************************************************************************************
12:40:23.060 [main] INFO  d.m.v.h.HighscoreResolver - Finished VPReg folder refresh of C:\Games\VPinExtensions\.\VPReg
12:40:23.060 [main] INFO  d.m.v.p.PopperManager - Finished Popper configuration check.
12:40:23.770 [main] INFO  o.e.j.u.log - Logging initialized @2162ms to org.eclipse.jetty.util.log.Slf4jLog
12:40:23.817 [main] INFO  o.e.j.s.Server - jetty-9.4.35.v20201120; built: 2020-11-20T21:17:03.964Z; git: bdc54f03a5e0a7e280fab27f55c3c75ee8da89fb; jvm 11.0.22+7-LTS
12:40:23.848 [main] INFO  o.e.j.s.AbstractConnector - Started ServerConnector@14dd7b39{HTTP/1.1, (http/1.1)}{0.0.0.0:8089}
12:40:23.848 [main] INFO  o.e.j.s.Server - Started @2242ms
12:40:23.895 [main] INFO  d.m.v.d.DOFManager - Starting Rule Engine
12:40:23.895 [main] INFO  d.m.v.VPinService - VPinService created [headless-mode]
12:40:23.895 [main] INFO  d.m.v.e.ServiceRunner - ServiceRunner started.
12:40:23.895 [main] INFO  d.m.v.e.ServiceRunner - Added VPin service listener for highscore changes.
12:40:23.911 [main] INFO  d.m.v.e.ServiceRunner - Executing highscore overlay generation.
12:40:23.911 [main] INFO  d.m.v.VPinService - Resetted game info list.
12:40:25.078 [main] INFO  d.m.v.VPinService - Starting Game Scan...
12:40:25.093 [main] INFO  d.m.v.VPinService - Loading of all GameInfo finished, loaded 74 games.
12:40:25.093 [main] INFO  d.m.v.h.HighscoreResolver - Parsing nvram file C:\Games\Visual Pinball\VPinMAME\nvram\trn_174h.nv
12:40:25.171 [main] INFO  d.m.v.e.g.OverlayGraphics - Rendering row for table Tron Legacy LE (Stern 2011), last played 2024-02-20
12:40:25.234 [main] INFO  d.m.v.h.HighscoreResolver - Parsing nvram file C:\Games\Visual Pinball\VPinMAME\nvram\acd_170h.nv
12:40:25.312 [main] INFO  d.m.v.e.g.OverlayGraphics - Rendering row for table AC-DC (Stern 2012), last played 2024-02-20
12:40:25.327 [main] INFO  d.m.v.e.g.OverlayGraphics - Rendering row for table 8 Ball (Williams 1966), last played 2024-02-20
12:40:25.327 [main] INFO  d.m.v.h.HighscoreResolver - Parsing nvram file C:\Games\Visual Pinball\VPinMAME\nvram\dw_l2.nv
12:40:25.406 [main] INFO  d.m.v.e.g.OverlayGraphics - Rendering row for table Doctor Who (Bally 1992), last played 2024-02-19
12:40:25.452 [main] INFO  d.m.v.e.g.OverlayGraphics - Rendering row for table Guardians of the Galaxy (Original 2020), last played 2024-02-16
12:40:25.468 [main] INFO  d.m.v.h.HighscoreResolver - Parsing nvram file C:\Games\Visual Pinball\VPinMAME\nvram\ft_l5.nv
12:40:25.546 [main] INFO  d.m.v.e.g.OverlayGraphics - Rendering row for table Fish Tales (Williams 1992), last played 2024-02-16
12:40:25.577 [main] INFO  d.m.v.h.HighscoreResolver - Parsing nvram file C:\Games\Visual Pinball\VPinMAME\nvram\tz_94h.nv
12:40:25.656 [main] INFO  d.m.v.e.g.OverlayGraphics - Rendering row for table Twilight Zone (Bally 1993), last played 2024-02-16
12:40:25.656 [main] INFO  d.m.v.h.HighscoreResolver - Parsing nvram file C:\Games\Visual Pinball\VPinMAME\nvram\bnzai_l3.nv
12:40:25.734 [main] INFO  d.m.v.e.g.OverlayGraphics - Rendering row for table Banzai Run (Williams 1988), last played 2024-02-16
12:40:25.749 [main] INFO  d.m.v.h.HighscoreResolver - Parsing nvram file C:\Games\Visual Pinball\VPinMAME\nvram\stwr_104.nv
12:40:25.827 [main] ERROR d.m.v.h.HighscoreResolver - Failed to parse highscore: Failed to read scores from output: Not supported rom : C:\Games\Visual Pinball\VPinMAME\nvram\stwr_104.nv

java.lang.Exception: Failed to read scores from output: Not supported rom : C:\Games\Visual Pinball\VPinMAME\nvram\stwr_104.nv

	at de.mephisto.vpin.highscores.HighscoreParser.parseHighscore(HighscoreParser.java:68)
	at de.mephisto.vpin.highscores.HighscoreResolver.parseNvHighscore(HighscoreResolver.java:237)
	at de.mephisto.vpin.highscores.HighscoreResolver.loadHighscore(HighscoreResolver.java:50)
	at de.mephisto.vpin.highscores.HighscoreManager.getHighscore(HighscoreManager.java:31)
	at de.mephisto.vpin.VPinService.getHighscore(VPinService.java:264)
	at de.mephisto.vpin.GameInfo.resolveHighscore(GameInfo.java:40)
	at de.mephisto.vpin.extensions.generator.OverlayGraphics.renderHighscoreList(OverlayGraphics.java:201)
	at de.mephisto.vpin.extensions.generator.OverlayGraphics.drawGames(OverlayGraphics.java:94)
	at de.mephisto.vpin.extensions.generator.OverlayGenerator.generate(OverlayGenerator.java:35)
	at de.mephisto.vpin.extensions.generator.OverlayGenerator.generateOverlay(OverlayGenerator.java:25)
	at de.mephisto.vpin.extensions.ServiceRunner.<init>(ServiceRunner.java:34)
	at de.mephisto.vpin.extensions.SuperMain.main(SuperMain.java:22)
12:40:25.827 [main] INFO  d.m.v.h.HighscoreResolver - Reading highscore for 'Star Wars (Data East 1992)' failed, no nvram file, no VPReg.stg entry and no highscore file found for rom name 'stwr_104'
12:40:25.827 [main] INFO  d.m.v.e.g.OverlayGraphics - Skipped highscore rendering of Star Wars (Data East 1992), no highscore info found
12:40:25.827 [main] INFO  d.m.v.e.g.OverlayGraphics - Rendering row for table The Matrix (Original), last played 2024-02-13
12:40:25.843 [main] INFO  d.m.v.h.HighscoreResolver - Parsing nvram file C:\Games\Visual Pinball\VPinMAME\nvram\br_l4.nv
12:40:25.921 [main] INFO  d.m.v.e.g.OverlayGraphics - Rendering row for table Black Rose (Bally 1992), last played 2024-02-13
12:40:25.921 [main] INFO  d.m.v.e.g.OverlayGraphics - Rendering row for table Game of Thrones LE (Stern 2015), last played 2024-02-12
12:40:25.952 [main] INFO  d.m.v.h.HighscoreResolver - Parsing nvram file C:\Games\Visual Pinball\VPinMAME\nvram\ripleys.nv
12:40:26.030 [main] INFO  d.m.v.e.g.OverlayGraphics - Rendering row for table Ripley's Believe or Not (Stern 2004), last played 2024-02-12
12:40:26.296 [main] INFO  d.m.v.u.ImageUtil - Writing C:\Games\VPinExtensions\.\resources\overlay.jpg took 187ms.
12:40:26.343 [main] INFO  d.m.v.e.ServiceRunner - Overlay window listener started.
12:40:26.730 [JavaFX Application Thread] INFO  d.m.v.e.g.OverlayGraphics - Added VPin service popper status listener.
12:40:32.445 [qtp1250142026-65] INFO  d.m.v.h.AsyncServlet - Received Popper launch event.
12:40:32.445 [qtp1250142026-65] INFO  d.m.v.e.g.OverlayGraphics - Received Popper Launch Event
12:40:42.464 [JNativeHook Dispatch Thread] INFO  d.m.v.e.g.OverlayGraphics - Kill switch key event 'X' (45)
12:40:42.464 [JNativeHook Dispatch Thread] INFO  d.m.v.e.g.OverlayGraphics - Killswitch pressed, restarting popper.
12:40:42.497 [JNativeHook Dispatch Thread] INFO  d.m.v.u.SystemInfo - Destroyed process 'C:\Games\PinUPSystem\PinUpMenu.exe', result: true
12:40:42.498 [JNativeHook Dispatch Thread] INFO  d.m.v.u.SystemInfo - Destroyed process 'C:\Games\PinUPSystem\PinUpDisplay.exe', result: true
12:40:42.503 [JNativeHook Dispatch Thread] INFO  d.m.v.u.SystemInfo - Destroyed process 'C:\Games\PinUPSystem\PinUpPlayer.exe', result: true
12:40:42.504 [JNativeHook Dispatch Thread] INFO  d.m.v.u.SystemInfo - Destroyed process 'C:\Games\PinUPSystem\PinUpDisplay.exe', result: true
12:40:42.688 [qtp1250142026-23] INFO  d.m.v.h.AsyncServlet - Received Popper launch event.
12:40:42.688 [qtp1250142026-23] INFO  d.m.v.e.g.OverlayGraphics - Received Popper Launch Event
12:40:56.786 [JNativeHook Dispatch Thread] INFO  d.m.v.e.g.OverlayGraphics - Kill switch key event 'X' (45)
12:40:56.786 [JNativeHook Dispatch Thread] INFO  d.m.v.e.g.OverlayGraphics - Killswitch pressed, restarting popper.
12:40:56.820 [JNativeHook Dispatch Thread] INFO  d.m.v.u.SystemInfo - Destroyed process 'C:\Games\PinUPSystem\PinUpMenu.exe', result: true
12:40:56.821 [JNativeHook Dispatch Thread] INFO  d.m.v.u.SystemInfo - Destroyed process 'C:\Games\PinUPSystem\PinUpDisplay.exe', result: true
12:40:56.824 [JNativeHook Dispatch Thread] INFO  d.m.v.u.SystemInfo - Destroyed process 'C:\Games\PinUPSystem\PinUpPlayer.exe', result: true
12:40:56.826 [JNativeHook Dispatch Thread] INFO  d.m.v.u.SystemInfo - Destroyed process 'C:\Games\PinUPSystem\PinUpDisplay.exe', result: true
12:40:57.004 [qtp1250142026-24] INFO  d.m.v.h.AsyncServlet - Received Popper launch event.
12:40:57.004 [qtp1250142026-24] INFO  d.m.v.e.g.OverlayGraphics - Received Popper Launch Event

**Comment by syd711** [comment]
Uh, this ticket is a nice suprise.
No, this project is not maintained anymore. 
But it has been re-implemented here: https://github.com/syd711/vpin-studio
